name: Deploy API to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate Python Code
      run: python -m py_compile server.py

    - name: Trigger Render Deploy
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl -X POST $RENDER_DEPLOY_HOOK_URL
